---
- name: Add ROS 2 apt signing key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    mode: "0644"

- name: Add ROS 2 apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ 'arm64' if ansible_machine == 'aarch64' else 'amd64' }}
      signed-by=/usr/share/keyrings/ros-archive-keyring.gpg]
      http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main
    filename: ros2
    state: present

- name: Install ROS 2 base
  ansible.builtin.apt:
    name: "ros-{{ ros_distro }}-ros-base"
    update_cache: true
    state: present

- name: Write ROS 2 login profile script
  ansible.builtin.copy:
    dest: /etc/profile.d/ros2.sh
    mode: "0644"
    content: |
      if [ -f /opt/ros/{{ ros_distro }}/setup.bash ]; then
        . /opt/ros/{{ ros_distro }}/setup.bash
      fi